#############################################################################
# DiffTop-1.0.0 make file                                                   #
#                                                                           #
# Authors: M. Guzzi, S.-O. Moch                                             #
#                                                                           #
# Makefile to compile and link FORTRAN programs                             #
#  									    #
# "make" compiles and links the specified main programs and modules,        #
# using the specified libraries (if any), and produces the executables      #
#									    #
# "make clean" removes all files generated by "make"                        #
#                                                                           #
#############################################################################


all: rmxeq  mkxeq
.PHONY: all

# main programs and modules to be compiled
MAIN= difftop1PI


#marco modules for 1PI kinematics
#MODULES =  wgplg integrandpty pac1 hadfold vegas rambo 
MODULES =  wgplg integrandpty-4top-cross-section-rambo pac1 hadfold vegas rambo_opt me.qQ2ttTT me.gg2tTtT

# Additional libraries for LHAPDF
LHLIB = LHAPDF
LHLIBPATH = $(shell lhapdf-config --prefix)/lib
#LHLIBPATH=/afs/desy.de/user/g/guzzim/share/lib64


############################## do not change #############################

SHELL=/bin/bash 
FF = gfortran
FFLAGS = -ffast-math -funroll-all-loops  -fPIC  -lm
#-O3
# Uncomment next line to profile the code
# FFLAGS += -g -pg

FLINKER=$(FF)

PGMS= $(MAIN) $(MODULES)

-include $(addsuffix .d,$(PGMS))

# rule to compile source programs

$(addsuffix .o,$(PGMS)): %.o: %.f Makefile
	$(FF) $< -c $(FFLAGS)

# rule to link object files

$(MAIN): %: %.o $(addsuffix .o,$(MODULES)) Makefile
	$(FLINKER) $< $(addsuffix .o,$(MODULES)) $(FFLAGS) \
        $(addprefix -L,$(LHLIBPATH)) $(addprefix -l,$(LHLIB)) \
		     -o $@


# produce executables

mkxeq: $(MAIN)

# remove old executables

rmxeq:
	@ -rm -f $(MAIN); \
        echo "delete old executables"

# clean directory

clean:
	@ -rm -rf *.o *~ *.log fort*  $(MAIN)
.PHONY: clean

################################################################################
